GET http://localhost:3001/api/posts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE

###
GET http://localhost:3001/api/posts/wall/vp
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE

###
GET http://localhost:3001/api/posts/6257fccb2efcbef8bf5d99ed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE

###
DELETE  http://localhost:3001/api/posts/6257fccb2efcbef8bf5d99ee
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE

###
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE


    {
        "src": "https://w2.chabad.org/media/images/1187/SvDB11878116.jpg?_i=_n504BC99DD0473598AAE3BCDC5D75568D",
        "caption": "Of Mugs and Family Ties",
        "owner": "newpaltz_benevolent",
        "likes": [],
        "comments": [],
        "isPublic": true
     }


###
PATCH http://localhost:3001/api/posts/6257fccb2efcbef8bf5d99ee
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE

{
    "owner": "newpaltz_benevolent"
}

###
POST http://localhost:3001/api/posts/seed
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU0NzU0ZmU0NDI4MWYwMzIzZTdmNDkiLCJmaXJzdE5hbWUiOiJEb25hbGQiLCJsYXN0TmFtZSI6IkNocmlzdGFuIiwiaGFuZGxlIjoiam9obmRvZSIsImVtYWlsIjoicHJlc2lkZW50QG5ld3BhbHR6LmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8xLmpwZyIsImlkIjo0LCJpYXQiOjE2NDk5NjYwNzh9.aVqNchNWiQTu5DHECwT0MB2QOAXA3Zkjravz-HQenOE
