http://localhost:3001

###
GET http://localhost:3001/api/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJWbGFkaW1pciIsImxhc3ROYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW4uY29tIiwicGljIjoiaHR0cHM6Ly9yYW5kb211c2VyLm1lL2FwaS9wb3J0cmFpdHMvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTA5ODU0Nn0.iFcxo-3tNjuKSYJSBQleWy5tmD3ea17HqfK0QS8vbGg

###
GET http://localhost:3001/api/users/handle/vp

###
DELETE http://localhost:3001/api/users/624f3d2d1d8558ee9a10c4cd
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJWbGFkaW1pciIsImxhc3ROYW1lIjoiUHV0aW4gSUlJIiwiaGFuZGxlIjoicnVzc2lhbl9kaWN0YXRvciIsImVtYWlsIjoic2F2ZUB1a3JhaW4uY29tIiwicGljIjoiaHR0cHM6Ly9yYW5kb211c2VyLm1lL2FwaS9wb3J0cmFpdHMvbWVuLzIuanBnIiwiaWQiOjIsImlhdCI6MTY0OTA5ODU0Nn0.iFcxo-3tNjuKSYJSBQleWy5tmD3ea17HqfK0QS8vbGg

###

POST http://localhost:3001/api/users
Content-Type: application/json

  {
    "firstName": "Donald",
    "lastName": "Christan",
    "handle": "johndoe",
    "password": "Hugo",
    "email": "president@newpaltz.edu",
    "pic": "https://randomuser.me/api/portraits/men/1.jpg"
    
  }

###

PATCH http://localhost:3001/api/users/2
Content-Type: application/json

  {
    "lastName": "Putin III",
    "password": "Ukraine",
    "email": "save@ukrain.com"


  }

###

POST http://localhost:3001/api/users/login
Content-Type: application/json

  {
    "email": "save@ukrain.com",
    "password": "Ukraine"
    
  }
###

POST http://localhost:3001/api/users/seed
Content-Type: application/json

  